name:                mutable
version:             0.1.0.0
github:              mstksg/mutable
license:             BSD3
author:              Justin Le
maintainer:          justin@jle.im
copyright:           (c) Justin Le 2019

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
synopsis:            Automatic piecewise-mutable references for your types
category:            Data

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: |
    Associate and generate "piecewise-mutable" versions for your composite data
    types.  Think of it like a "generalized MVector for all ADTs".

    Useful for a situation where you have a record with many fields (or many nested
    records) that you want to use for efficient mutable in-place algorithms.  This
    library lets you do efficient "piecewise" mutations (operations that only edit
    one field), and also efficient entire-datatype copies/updates, as well, in many
    cases.

    See <https://mutable.jle.im> for official introduction and documentation,
    or jump right in by importing "Data.Mutable".

ghc-options:
- -Wall
- -Wcompat
- -Wredundant-constraints
- -Werror=incomplete-patterns

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  other-modules:
  - Data.Mutable.Internal
  dependencies:
  - array
  - constraints
  - generic-lens
  - primitive
  - reflection
  - transformers
  - vector
  - vinyl

benchmarks:
  mutable-bench:
    main: bench.hs
    source-dirs: bench
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - criterion
    - deepseq
    - directory
    - microlens
    - microlens-th
    - mutable
    - time
    - transformers
    - vector
    - vinyl

# executables:
#   mutable-exe:
#     main:                Main.hs
#     source-dirs:         app
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - mutable

# tests:
#   mutable-test:
#     main:                Spec.hs
#     source-dirs:         test
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - mutable
